routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::namespace('Account')->group(function () {

	Route::get('/', function () {
	    return view('Account/login');
	});
	Route::post('/check_user', 'AccountController@login_user');
	Route::get('/logout/admin','AccountController@logout_admin')->name('logout.admin');


	Route::get('/logout/user','AccountController@logout_user')->name('logout.user');

	// logout_user
	Route::get('/home/register', 'AccountController@register')->name('home.register');

	// registration
 	Route::post('/user/add', 'SignupController@add')->name('user.add');


 	Route::get('/forgot_password', function(){
	    return view('Account.forgot_password');
	  });

	 Route::post('get_token/{user_type}', 'ForgotPasswordController@get_token');
	 Route::get('/new_password/{token}/{id}', 'ForgotPasswordController@new_password')->name('account.new_password');
	 Route::get('/verify_account/{token}/{id}', 'AccountController@verify_account')->name('account.verify');

	 Route::post('/create_new_password/{token}/{id}', 'ForgotPasswordController@create_new_password');

});


Route::namespace('Admin')->group(function () {
	Route::middleware(['auth:admin'])->group(function () {

   		Route::get('/Admin/config', function(){
					return view('Admin.account_settings');
			})->middleware('auth:admin');

		Route::get('/admin', 'AdminController@index')->name('admin.index');

		// Account
		 Route::get('/account/list', 'AccountController@list')->name('account.list');
		 Route::post('/account/add', 'AccountController@add')->name('account.add');
		 Route::get('/account/delete/{id}', 'AccountController@delete_account')->name('account.delete');

		 // Account Password
		 Route::post('/password/change_password', 'AccountController@change_password')->name('password.change_password');


		// Student
		Route::get('/admin/student', 'StudentController@index')->name('admin.student.index');
		Route::post('/student_add', 'StudentController@add')->name('admin.student.add');
		Route::get('/student/list', 'StudentController@list')->name('admin.student.list');
		Route::get('/student/delete/{user_id}', 'StudentController@student_delete')->name('admin.student.delete');

		// Teacher
		Route::get('/admin/teacher', 'TeacherController@index')->name('admin.teacher.index');
		Route::get('/teacher/list', 'TeacherController@list')->name('teacher.list');
		Route::post('/teacher/add', 'TeacherController@add')->name('teacher.add');
		Route::get('/teacher/delete/{id}', 'TeacherController@delete_teacher')->name('teacher.delete');

		// Promo Code
  		 Route::get('/admin/promo', 'PromoController@index')->name('admin.promo.index');
		 Route::get('/promo/list', 'PromoController@list')->name('promo.list');
		 Route::post('/promo/add', 'PromoController@add')->name('promo.add');
		 Route::get('/promo/delete/{promo_id}', 'PromoController@delete_promo')->name('promo.delete');

		 // Bundle
		Route::get('/admin/bundle', 'BundleController@index')->name('admin.promo.index');
		Route::get('/bundle/list', 'BundleController@list')->name('bundle.list');
		Route::post('/bundle/add', 'BundleController@add')->name('bundle.add');
		Route::get('/bundle/delete/{bundle_id}', 'BundleController@delete_bundle')->name('bundle.delete');
		// Form
		Route::get('/form/dropdown', 'FormController@dropdown')->name('admin.form.dropdown');

		Route::get('/form/list', 'FormController@list')->name('admin.form.list');
		Route::get('admin/form', 'FormController@index')->name('admin.form.index');
		Route::get('admin/form/edit/{form_id}', 'FormController@edit')->name('admin.form.edit');
		Route::post('admin/form/create', 'FormController@add')->name('admin.form.add');
		Route::post('/form/add/category', 'FormController@add_form_category');
		Route::get('/form/delete/{mainform_id}', 'FormController@delete_forms')->name('mainform.delete');
		Route::get('/form/category/question/{mainform_id}', 'FormController@get_category_question')->name('form.category.question');
		Route::get('/form/category/delete/{form_detail_id}', 'FormController@form_detail_delete')->name('form.detail.action');

		// Manual selection
		Route::get('admin/form/manual/edit/{form_id}', 'FormManualController@edit')->name('admin.form_manual.edit');
		Route::get('/form/category/question/manual/{mainform_id}', 'FormManualController@get_category_question')->name('form.category.question_manual');
		Route::post('/form/save/order', 'FormManualController@save_form_order')->name('save_manual.order');


		// Generator
	  // Route::post('/generate_form_order/{mainform_id}', 'FormController@form_order');

		// Category
		Route::get('/category/list', 'CategoryController@list')->name('category.list');
		Route::get('admin/category', 'CategoryController@index')->name('admin.category.index');
		Route::get('admin/category/edit/{category_id}', 'CategoryController@edit')->name('admin.category.edit');
		Route::post('admin/category/create', 'CategoryController@add')->name('admin.category.add');
		Route::get('category/question/{category_id}', 'CategoryController@get_question')->name('admin.category.question');
		Route::get('/admin/category/delete/{category_id}', 'CategoryController@delete_category')->name('admin.category_id.delete');
		// Question
		Route::get('/question/find/{id}', 'CategoryController@find_question')->name('question.find');
	 	Route::post('/question/add', 'CategoryController@question_add')->name('question.add');
    Route::post('/choices/add', 'CategoryController@choices_add')->name('choices.add');
		Route::get('/delete/question/{question_id}', 'CategoryController@delete_question')->name('question.delete');

 	    //Choices
 	    Route::get('/question/choice/{question_id?}', 'CategoryController@get_choices')->name('choices.list');
 	    Route::get('/choices/delete/{choice_id}', 'CategoryController@delete_choices')->name('choice.delete');


			// Group category
			Route::get('/admin/group/category', function(){
					return view('GroupCategory.index');
			})->name('group.category');

			Route::get('/group/list_group/find/{id}', 'GroupCategoryController@list_group_find')->name('group.find');
			Route::get('/group/list_group_member/find/{id}', 'GroupCategoryController@list_group_member_find')->name('group.find.member');

			Route::get('/group/list_user_group/find', 'GroupCategoryController@list_user_group_find')->name('user.group.find');
			Route::get('/mygroup/show/{id}', 'GroupCategoryController@show_my_group')->name('user.mygroup.show');

			Route::get('/group/list_group', 'GroupCategoryController@list_group')->name('group.list');
			Route::post('/group/add_group', 'GroupCategoryController@add_group')->name('group.add');
			Route::get('/group/delete_group/{group_category_id}', 'GroupCategoryController@delete_group')->name('group.delete');


			// Group
			 Route::get('/g_member/delete_g_member/{group_id}', 'GroupController@delete_g_member')->name('g_member.delete');

			 // Test form check by teacher
			 Route::get('/admin/test/check', function(){
				 return view('Teacher.checkforms');
			 });

			 Route::get('/teacher/check_list', 'CheckController@checking_form_list')->name('check.list');

			 // Open the form Checking modal
			 Route::get('/teacher/check/{id?}', 'CheckController@get_question_from_answer')->name('check.answer.form');


			 Route::get('/testing/check/{id?}', 'CheckController@save_purchase')->name('check.test.form');

			 // Add score
			 Route::post('/teacher/score/question', 'CheckController@add_score')->name('group.add');



	});
});


Route::namespace('Inventory')->group(function () {
	Route::middleware(['auth:admin'])->group(function () {

		Route::get('/admin/inventory', 'InventoryController@index')->name('product.index');
		Route::get('/inventory/list', 'InventoryController@list')->name('product.list');
		Route::post('/product/add', 'InventoryController@add_product')->name('product.add');
		Route::get('/product/delete/{product_id}', 'InventoryController@delete_product')->name('product.delete');


	});



});


Route::namespace('Form')->group(function () {

});


Route::namespace('Student')->group(function () {
	Route::middleware(['auth'])->group(function () {

		Route::get('/student/config', function(){
			return view('Student.account_settings');
		});

		// Account
		Route::post('/student/account/add', 'AccountController@add')->name('student.account.add');
		Route::post('/student/password/change_password', 'AccountController@change_password')->name('student.password.change_password');

		Route::get('/student', 'ShopController@index')->name('student.index');
		Route::get('/student/shop/', 'ShopController@shop')->name('student.shop');

 	 	Route::get('/product/list', 'ShopController@list')->name('product.list');
	 	Route::post('/student/buy/form', 'PurchasedController@add')->name('purchased.add');


		Route::get('/student/form', 'PurchasedController@index')->name('student.form');
	 	// Purchased
	 	Route::get('/purchased/list', 'PurchasedController@list')->name('purchased.list');

	 	// Exam form

	 	Route::get('/student/exam/{purchased_id}', 'ExamController@exam')->name('student.exam');
	 	Route::get('/get/exam/form/{purchased_id}', 'ExamController@get_exam')->name('student.purchased.exam');

		Route::get('/get/exam/review/{purchased_id}', 'ExamController@get_review')->name('student.purchased.review');
	 	Route::post('/save/answer', 'ExamController@make_answer')->name('student.question.answer');
		Route::post('/save/custom_answer', 'ExamController@make_custom_answer')->name('student.question.answer.custom');


	 	// result
	 	 Route::post('/result/add', 'ExamController@submit_form')->name('result.add');

	 	// test route result

app/Admin.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Hash;


class Admin extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */

    protected $table = 'sm_admin';


    protected $fillable = [
        'profile_picture','name', 'email', 'username', 'password', 'date_deleted'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */

      public function mainform()
    {
        return $this->morphMany('App\MainForm', 'owner')->whereNull('deleted_at');
    }

      public function category()
    {
        return $this->morphMany('App\Category', 'owner')->whereNull('deleted_at');;
    }


       public function product()
    {
        return $this->morphMany('App\Product', 'owner')->whereNull('deleted_at');
    }

        public function bundle()
    {
        return $this->morphMany('App\Bundle', 'owner')->whereNull('deleted_at');
    }

    public function forgot(){
        return $this->morphMany('App\ForgotPassword', 'forgotable');
    }

    public function UserGroup()
    {
        return $this->morphMany('App\Group', 'groupable');
    }

      public function setPasswordAttribute($value){
        $this->attributes['password'] = Hash::make($value);
    }

    public function getCreatedAtAttribute($value)
    {
        return  \Carbon\Carbon::parse($value)->format('jS F Y');
    }

}

resources/views/Admin/account_settings.blade.php
<!DOCTYPE html>
<html>
	@include('Layout.header', ['type' => 'admin', 'title' => 'admin', 'icon' => asset('img/logophone.png') ])

<body class="font-base">
	@include('Layout.nav', ['type' => 'admin'])
	<div class="container-fluid mobile-margin">
		<div class="row">
			<div class="col-sm-12">
				<div class="card">
					<div class="card-header">Account Settings</div>
					<div class="card-body">
						<div class="row">
							<div class="col-sm-6 mb-2">
								<div class="card">
									<div class="card-header">Profile</div>
									<div class="card-body">
										<ul class="list-group">
											<li class="list-group-item "><span><b>Name</b></span> <span class="float-right text-tiny">{{ Auth::guard('admin')->user()->name }}</span></li>
											<li class="list-group-item"><span><b>Username</b></span> <span class="float-right text-tiny">{{ Auth::guard('admin')->user()->username }}</span></li>
											<li class="list-group-item"><span><b>Date Registered</b></span> <span class="float-right text-tiny">{{ Auth::guard('admin')->user()->created_at }}</span></li>
										</ul>
									</div>
								</div>
							</div>
							<div class="col-sm-6 mb-2">
								<div class="card">
									<div class="card-header">Account Settings</div>
									<div class="card-body">
										<form class="needs-validation" id="account_change_form" action="{{ url('account/add') }}" novalidate>
										<div class="form-row">
											<input type="hidden" id="id" name="id" value="{{ Auth::guard('admin')->user()->id }}" placeholder="" class="form-control" required>
											<div class="form-group col-sm-12">
												<label>Name </label>
												<input type="text" id="name" name="name" value="{{ Auth::guard('admin')->user()->name }}" placeholder="Name" class="form-control " required>
												<div class="invalid-feedback" id="err_name"></div>
											</div>
											<div class="form-group col-sm-12">
												<label>Username </label>
												<input type="text" id="username" name="username" value="{{ Auth::guard('admin')->user()->username }}" placeholder="Username" class="form-control " required>
												<div class="invalid-feedback" id="err_username"></div>
											</div>
											<div class="form-group col-sm-12">
												<label>Email </label>
												<input type="email" id="email" name="email" value="{{ Auth::guard('admin')->user()->email }}" placeholder="Email" class="form-control " required>
												<div class="invalid-feedback" id="err_email"></div>
											</div>

											<div class="col-sm-12 text-right">
												<button class="btn btn-dark btn-sm" type="submit">Save</button>
												<button class="btn btn-light btn-sm border-dark" onclick="change_password();" type="button">Change Password</button>
											</div>
										</div>
									</form>

									</div>
								</div>
							</div>
						</div>
					</div>
					<div class="card-footer"></div>
				</div>
			</div>
		</div>
	</div>
</body>
	@include('Layout.footer', ['type' => 'admin'])
</html>

 <div class="modal fade" role="dialog" id="modal_change_password">
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-header">
            <div class="modal-title">
            Change Password
            </div>
            <button class="close" data-dismiss="modal">&times;</button>
          </div>
          <div class="modal-body">
            <form class="needs-validation" id="account_change_password" action="{{ url('password/change_password') }}" novalidate>
				<div class="form-row">
					<div class="form-group col-sm-12">
						<label>Old Password </label>
						<input type="password" id="old_password" name="old_password" placeholder="Old Password" class="form-control " required>
						<div class="invalid-feedback" id="err_old_password"></div>
					</div>
					<div class="form-group col-sm-12">
						<label>New Password </label>
						<input type="password" id="new_password" name="new_password" placeholder="New Password" class="form-control " required>
						<div class="invalid-feedback" id="err_new_password"></div>
					</div>
					<div class="form-group col-sm-12">
						<label>Confirm Password </label>
						<input type="password" id="confirm_password" name="confirm_password" placeholder="Confirm Password" class="form-control " required>
						<div class="invalid-feedback" id="err_confirm_password"></div>
					</div>

					<div class="col-sm-12 text-right">
						<button class="btn btn-dark btn-sm" type="submit">Save Changes</button>
					</div>
				</div>
			</form>

          </div>
          <div class="modal-footer">
            
          </div>
        </div>
      </div>
    </div>


<script type="text/javascript">
	function change_password(){
		clear_password_form();
		$("#modal_change_password").modal('show');
	}

	$("#account_change_form").on('submit', function(e){
		var url = $(this).attr('action');
		var mydata = $(this).serialize();
		e.stopPropagation();
		e.preventDefault(e);

		$.ajax({
			type:"POST",
			url:url,
			data:mydata,
			cache:false,
			beforeSend:function(){
					//<!-- your before success function -->
			},
			success:function(response){
				if(response.status == true){
					// console.log(response)
					swal("Success",response.message,"success");
					showValidator(response.error,'account_change_form');
				}else{
					//<!-- your error message or action here! -->
					showValidator(response.error,'account_change_form');
				}
			},
			error:function(error){
				console.log(error)
			}
		});
	});
</script>

<script type="text/javascript">
$("#account_change_password").on('submit', function(e){
	var url = $(this).attr('action');
	var mydata = $(this).serialize();
	e.stopPropagation();
	e.preventDefault(e);

	$.ajax({
		type:"POST",
		url:url,
		data:mydata,
		cache:false,
		beforeSend:function(){
				//<!-- your before success function -->
		},
		success:function(response){
			if(response.status == true){
				console.log(response)
				swal("Success",response.message,"success");
				showValidator(response.error,'account_change_password');
				$("#modal_change_password").modal('hide');
				clear_password_form();
			}else{
				//<!-- your error message or action here! -->
				showValidator(response.error,'account_change_password');
			}
		},
		error:function(error){
			console.log(error)
		}
	});
});

function clear_password_form(){
	$("#old_password").val('');
	$("#new_password").val('');
	$("#confirm_password").val('');
}
</script>

resources/views/Admin/bundle.blade.php
<!DOCTYPE html>
<html>
	@include('Layout.header', ['type' => 'admin', 'title' => 'Bundle', 'icon' => asset('img/logophone.png') ])
<style type="text/css">
	#tbl_product_list_wrapper .col-sm-12{
		padding:10px !important;
	}
</style>
<body class="font-base" onload="show_bundle();">
	@include('Layout.nav', ['type' => 'admin'])
	<div class="container-fluid mobile-margin">
		<div class="row">
			<div class="col-sm-12">
				<div class="card">
					<div class="card-header">Bundle Product
						<button class="btn btn-primary btn-sm float-right" onclick="add_bundle();"><i class="fa fa-plus"></i> Add Bundle</button>
					</div>
					<div class="card-body">
						<table class="table table-bordered dt-responsive nowrap" id="tbl_bundle" style="width: 100%;"></table>
					</div>
					<div class="card-footer"></div>
				</div>
			</div>
		</div>
	</div>
</body>
	@include('Layout.footer', ['type' => 'admin'])
</html>

 <div class="modal fade" role="dialog" id="modal_add_bundle">
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-header">
            <div class="modal-title">
            Add Product Bundle
            </div>
            <button class="close" data-dismiss="modal">&times;</button>
          </div>
          <div class="modal-body">
            <form class="needs-validation" id="bundle_add_form" action="{{ url('bundle/add') }}" novalidate>
				<div class="form-row">
					<input type="hidden" id="bundle_id" name="bundle_id" placeholder="" class="form-control" required>
					<div class="form-group col-sm-12">
						<label>Bundle Name </label>
						<input type="text" id="bundle_name" name="bundle_name" placeholder="Bundle Name" class="form-control " required>
						<div class="invalid-feedback" id="err_bundle_name"></div>
					</div>
					<div class="form-group col-sm-12">
						<label>Bundle Price </label>
						<input type="number" id="bundle_price" name="bundle_price" placeholder="Bundle Price" class="form-control " required>
						<div class="invalid-feedback" id="err_bundle_price"></div>
					</div>

					<div class="col-sm-12">
						<hr>
						<label>Select Product</label>
						<table class="table table-bordered dt-responsive nowrap" id="tbl_product_list" style="width: 100% !important;">
							<thead>
								<tr>
									<th><input type="checkbox" name="select_all" id="select_all" class="check_all"></th>
									<th>Product Name</th>
									<th>Price</th>
								</tr>
							</thead>

							<tbody>
								@foreach($product as $row)
								<tr>
									<td><input type="checkbox" name="product_item[{{ $row->product_id }}]" value="{{ $row->product_id }}" id="select_item_{{ $row->product_id }}" class="check_item"></td>
									<td>{{ $row->mainform->name }}</td>
									<td>{{ $row->price }}</td>
								</tr>
								@endforeach
							</tbody>
						</table>
					</div>

					<div class="col-sm-12 text-right">
						<button class="btn btn-dark btn-sm" type="submit">Save</button>
					</div>
				</div>
			</form>
          </div>
          <div class="modal-footer">
            
          </div>
        </div>
      </div>
    </div>


    <!-- Javascript Function-->
<script>

	$(document).ready(function(){
	    $(".check_all").click(function(){
	    	if ($(this).prop('checked')) {
	    		$(".check_item").prop("checked", true);
	    	}else{
    			$(".check_item").prop("checked", false);
	    	}
	    });
	
		$(".check_item").on('input', function(){
			var selector = $("#select_all");

		   if ($('.check_item:checked').length == $('.check_item').length) {
				selector.prop("checked", true);
	    	}else{
				selector.prop("checked", false);
	    	}
		});

	});

	function check_checkbox(){
		var selector = $("#select_all");

	   if ($('.check_item:checked').length == $('.check_item').length) {
			selector.prop("checked", true);
    	}else{
			selector.prop("checked", false);
    	}
	}


	$("#tbl_product_list").dataTable();

	function add_bundle(){
		clear_bundle_form();
		$(".check_item").prop("checked", false);
		$(".check_all").prop("checked", false);
		$("#modal_add_bundle").modal('show');
	}

	var tbl_bundle;
	function show_bundle(){
		if (tbl_bundle) {
			tbl_bundle.destroy();
		}
		var url = main_path + '/bundle/list';
		tbl_bundle = $('#tbl_bundle').DataTable({
		pageLength: 10,
		responsive: true,
		ajax: url,
		deferRender: true,
		language: {
		"emptyTable": "No data available"
	},
		columns: [{
		className: '',
		"data": "bundle_name",
		"title": "Bundle Name",
	},{
		className: '',
		"data": "bundle_price",
		"title": "Bundle Price",
	},{
		className: 'width-option-1 text-center',
		"data": "bundle_id",
		"orderable": false,
		"title": "Options",
			"render": function(data, type, row, meta){
				var param_data = JSON.stringify(row);
				newdata = '';
				newdata += '<button class="btn btn-success btn-sm font-base mt-1" data-info=\''+param_data.trim()+'\' onclick="edit_bundle(this)" type="button"><i class="fa fa-edit"></i> Edit</button> ';
				newdata += '<button class="btn btn-danger btn-sm font-base mt-1" data-info=\''+param_data.trim()+'\' onclick="delete_bundle(this)" type="button"><i class="fa fa-edit"></i> delete</button>';
				return newdata;
			}
		}
	]
	});
	}

	$("#bundle_add_form").on('submit', function(e){
		var url = $(this).attr('action');
		var mydata = $(this).serialize();
		e.stopPropagation();
		e.preventDefault(e);

		// alert(mydata);

		$.ajax({
			type:"POST",
			url:url,
			data:mydata,
			cache:false,
			beforeSend:function(){
					//<!-- your before success function -->
			},
			success:function(response){
				if(response.status == true){
					// console.log(response)
					clear_bundle_form();
					$("#modal_add_bundle").modal('hide');
					show_bundle();
					swal("Success", response.message, "success");
					showValidator(response.error,'bundle_add_form');
				}else{
					//<!-- your error message or action here! -->
					showValidator(response.error,'bundle_add_form');
				}
			},
			error:function(error){
				console.log(error)
			}
		});
	});

	function delete_bundle(_this){
		var data = JSON.parse($(_this).attr('data-info'));
		var url =  main_path + '/bundle/delete/' + data.bundle_id;
			swal({
				title: "Are you sure?",
				text: "Do you want to delete this bundle?",
				type: "warning",
				showCancelButton: true,
				confirmButtonColor: "#DD6B55",
				confirmButtonText: "Yes",
				closeOnConfirm: false
			},
			function(){
				$.ajax({
				type:"GET",
				url:url,
				data:{},
				dataType:'json',
				beforeSend:function(){
			},
			success:function(response){
				// console.log(response);
				if (response.status == true) {
					show_bundle();
					swal("Success", response.message, "success");
				}else{
					console.log(response);
				}
			},
			error: function(error){
				console.log(error);
			}
			});
		});
	}

	function clear_bundle_form(){
		$('#bundle_id').val('');
		$('#bundle_name').val('');
		$('#bundle_price').val('');
	}

	function edit_bundle(_this){
		var data = JSON.parse($(_this).attr('data-info'));
		// console.log(data.items[0].product_id);

		for (var i = 0; i < data.items.length; i++) {
			// console.log(data.items[i]);
			$("#select_item_" + data.items[i].product_id).prop('checked', true);
		}
		check_checkbox();

		$('#bundle_id').val(data.bundle_id);
		$('#bundle_name').val(data.bundle_name);
		$('#bundle_price').val(data.bundle_price);
		$("#modal_add_bundle").modal('show');
	}
</script>